/** Tailwind recipes for the DOM created by the map providers. */
export const MAP_MARKER_CLASSES = String.raw`tc-marker inline-flex items-center justify-center w-7 h-7 rounded-full font-body font-bold leading-[1] text-white bg-accent-deep cursor-pointer p-0 [border:2px_solid_#ffffff] [font-size:13px] [box-shadow:0_2px_6px_rgba(28,_25,_23,_0.28)] [transition:transform_var(--dur)_var(--ease-out),_box-shadow_var(--dur)_var(--ease-out)] [&.tc-marker--stop]:[z-index:2] [&.tc-marker--stay]:bg-stay-ink [&.tc-marker--stay]:[font-size:12px] [&.tc-marker--stay]:[z-index:1] [&.tc-marker--stay.tc-marker--offset]:w-5 [&.tc-marker--stay.tc-marker--offset]:h-5 [&.tc-marker--stay.tc-marker--offset]:[font-size:10px] [&.tc-marker--stay.tc-marker--offset]:[margin:-14px_0_0_16px] [&[aria-pressed='true']]:[transform:scale(1.2)] [&[aria-pressed='true']]:[box-shadow:0_0_0_4px_rgba(47,_95,_219,_0.22),_0_4px_10px_rgba(28,_25,_23,_0.3)] [&[aria-pressed='true']]:[z-index:3] [&.tc-marker--mini]:w-4.5 [&.tc-marker--mini]:h-4.5 [&.tc-marker--mini]:cursor-default [&.tc-marker--mini]:[font-size:10px] [&.tc-marker--mini]:[box-shadow:none] [&.tc-marker--mini]:[border-width:1.5px] [.tc-fixture-map\_\_layer_&]:absolute [.tc-fixture-map\_\_layer_&]:[transform:translate(-50%,_-50%)] [.tc-fixture-map\_\_layer_&[aria-pressed='true']]:[transform:translate(-50%,_-50%)_scale(1.2)]`;
/**
 * 큰 지도의 주변 장소 핀(2026-10-01). 분류 색으로 채운 작은 원에 흰 아이콘·흰 테두리.
 * 담은 곳은 흰 원에 분류 색 체크로 바뀐다. 평점을 읽었으면 옆에 작은 평점 표시를 붙인다.
 */
export const PLACE_PIN_ROOT_CLASSES = String.raw`tc-pin-root inline-flex items-center gap-0.5 [margin-left:-12px] [.tc-fixture-map\_\_layer_&]:absolute [.tc-fixture-map\_\_layer_&]:[transform:translateY(-50%)] [&:has([aria-pressed='true'])]:[z-index:4]`;
export const PLACE_PIN_CLASSES = String.raw`tc-pin inline-flex flex-none items-center justify-center size-6 rounded-full cursor-pointer p-0 text-white [border:2px_solid_#ffffff] [box-shadow:0_1px_4px_rgba(28,_25,_23,_0.3)] [transition:transform_var(--dur)_var(--ease-out)] [&.tc-pin--meal]:bg-meal-ink [&.tc-pin--cafe]:bg-cafe-ink [&.tc-pin--sight]:bg-place-ink [&.tc-pin--stay]:bg-stay-ink [&.tc-pin--added]:bg-panel [&.tc-pin--added.tc-pin--meal]:text-meal-ink [&.tc-pin--added.tc-pin--cafe]:text-cafe-ink [&.tc-pin--added.tc-pin--sight]:text-place-ink [&.tc-pin--added.tc-pin--stay]:text-stay-ink [&.tc-pin--added]:[border-color:currentColor] [&.tc-pin--candidate]:bg-ground-2! [&.tc-pin--candidate]:text-ink-3! [&[aria-pressed='true']]:[transform:scale(1.25)] [&[aria-pressed='true']]:[box-shadow:0_0_0_3px_rgba(47,_95,_219,_0.25),_0_2px_6px_rgba(28,_25,_23,_0.3)]`;
export const PLACE_PIN_RATING_CLASSES = String.raw`tc-pin-rating rounded-pill bg-panel px-1 py-px font-body text-[10px] font-bold leading-[1.4] text-ink [box-shadow:0_1px_3px_rgba(28,_25,_23,_0.25)] whitespace-nowrap`;
/** 내 위치 점. 파란 점에 흰 테두리와 옅은 테두리 빛. */
export const MY_LOCATION_CLASSES = String.raw`tc-me block size-4 rounded-full bg-accent-deep [border:3px_solid_#ffffff] [box-shadow:0_0_0_6px_rgba(47,_95,_219,_0.2),_0_1px_4px_rgba(28,_25,_23,_0.3)] [margin:-8px_0_0_-8px] [.tc-fixture-map\_\_layer_&]:absolute`;
export const FIXTURE_MAP_CLASSES = String.raw`tc-fixture-map relative [background:linear-gradient(var(--color-border)_1px,_transparent_1px)_0_0_/_40px_40px,_linear-gradient(90deg,_var(--color-border)_1px,_transparent_1px)_0_0_/_40px_40px,_var(--color-ground-2)]`;
export const FIXTURE_LAYER_CLASSES = String.raw`tc-fixture-map__layer absolute [inset:0]`;
