/*
  이 파일은 scripts/build-region-data.mjs가 만든다. 직접 고치지 않는다.

  원본은 public/geo/korea-municipalities-2026.geo.json이며 2026-07-01 기준
  행정구역이다. 지역을 더하거나 빼려면 경계 파일을 바꾼 뒤 스크립트를 다시
  돌린다. 그래야 지도에 있는 지역과 목록이 어긋나지 않는다.
*/
import type { KoreaProvince, KoreaRegion } from './korea-regions.types';

/** 시·도 16개. */
export const PROVINCE_DATA: readonly KoreaProvince[] = [
  { code: '11', name: '서울특별시', short: '서울' },
  { code: '12', name: '전남광주통합특별시', short: '전남광주' },
  { code: '26', name: '부산광역시', short: '부산' },
  { code: '27', name: '대구광역시', short: '대구' },
  { code: '28', name: '인천광역시', short: '인천' },
  { code: '30', name: '대전광역시', short: '대전' },
  { code: '31', name: '울산광역시', short: '울산' },
  { code: '36', name: '세종특별자치시', short: '세종' },
  { code: '41', name: '경기도', short: '경기' },
  { code: '43', name: '충청북도', short: '충북' },
  { code: '44', name: '충청남도', short: '충남' },
  { code: '47', name: '경상북도', short: '경북' },
  { code: '48', name: '경상남도', short: '경남' },
  { code: '50', name: '제주특별자치도', short: '제주' },
  { code: '51', name: '강원특별자치도', short: '강원' },
  { code: '52', name: '전북특별자치도', short: '전북' },
];

/** 시·군·구 230개. 코드 순으로 둔다. */
export const REGION_DATA: readonly KoreaRegion[] = [
  { code: '11_강남구', name: '강남구', label: '강남구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_강동구', name: '강동구', label: '강동구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_강북구', name: '강북구', label: '강북구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_강서구', name: '강서구', label: '강서구(서울)', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_관악구', name: '관악구', label: '관악구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_광진구', name: '광진구', label: '광진구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_구로구', name: '구로구', label: '구로구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_금천구', name: '금천구', label: '금천구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_노원구', name: '노원구', label: '노원구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_도봉구', name: '도봉구', label: '도봉구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_동대문구', name: '동대문구', label: '동대문구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_동작구', name: '동작구', label: '동작구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_마포구', name: '마포구', label: '마포구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_서대문구', name: '서대문구', label: '서대문구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_서초구', name: '서초구', label: '서초구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_성동구', name: '성동구', label: '성동구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_성북구', name: '성북구', label: '성북구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_송파구', name: '송파구', label: '송파구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_양천구', name: '양천구', label: '양천구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_영등포구', name: '영등포구', label: '영등포구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_용산구', name: '용산구', label: '용산구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_은평구', name: '은평구', label: '은평구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_종로구', name: '종로구', label: '종로구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_중구', name: '중구', label: '중구(서울)', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '11_중랑구', name: '중랑구', label: '중랑구', province: '서울특별시', provinceCode: '11', short: '서울' },
  { code: '12_강진군', name: '강진군', label: '강진군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_고흥군', name: '고흥군', label: '고흥군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_곡성군', name: '곡성군', label: '곡성군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_광산구', name: '광산구', label: '광산구', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_광양시', name: '광양시', label: '광양시', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_구례군', name: '구례군', label: '구례군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_나주시', name: '나주시', label: '나주시', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_남구', name: '남구', label: '남구(전남광주)', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_담양군', name: '담양군', label: '담양군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_동구', name: '동구', label: '동구(전남광주)', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_목포시', name: '목포시', label: '목포시', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_무안군', name: '무안군', label: '무안군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_보성군', name: '보성군', label: '보성군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_북구', name: '북구', label: '북구(전남광주)', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_서구', name: '서구', label: '서구(전남광주)', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_순천시', name: '순천시', label: '순천시', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_신안군', name: '신안군', label: '신안군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_여수시', name: '여수시', label: '여수시', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_영광군', name: '영광군', label: '영광군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_영암군', name: '영암군', label: '영암군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_완도군', name: '완도군', label: '완도군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_장성군', name: '장성군', label: '장성군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_장흥군', name: '장흥군', label: '장흥군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_진도군', name: '진도군', label: '진도군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_함평군', name: '함평군', label: '함평군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_해남군', name: '해남군', label: '해남군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '12_화순군', name: '화순군', label: '화순군', province: '전남광주통합특별시', provinceCode: '12', short: '전남광주' },
  { code: '26_강서구', name: '강서구', label: '강서구(부산)', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_금정구', name: '금정구', label: '금정구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_기장군', name: '기장군', label: '기장군', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_남구', name: '남구', label: '남구(부산)', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_동구', name: '동구', label: '동구(부산)', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_동래구', name: '동래구', label: '동래구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_부산진구', name: '부산진구', label: '부산진구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_북구', name: '북구', label: '북구(부산)', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_사상구', name: '사상구', label: '사상구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_사하구', name: '사하구', label: '사하구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_서구', name: '서구', label: '서구(부산)', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_수영구', name: '수영구', label: '수영구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_연제구', name: '연제구', label: '연제구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_영도구', name: '영도구', label: '영도구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_중구', name: '중구', label: '중구(부산)', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '26_해운대구', name: '해운대구', label: '해운대구', province: '부산광역시', provinceCode: '26', short: '부산' },
  { code: '27_군위군', name: '군위군', label: '군위군', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_남구', name: '남구', label: '남구(대구)', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_달서구', name: '달서구', label: '달서구', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_달성군', name: '달성군', label: '달성군', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_동구', name: '동구', label: '동구(대구)', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_북구', name: '북구', label: '북구(대구)', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_서구', name: '서구', label: '서구(대구)', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_수성구', name: '수성구', label: '수성구', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '27_중구', name: '중구', label: '중구(대구)', province: '대구광역시', provinceCode: '27', short: '대구' },
  { code: '28_강화군', name: '강화군', label: '강화군', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_검단구', name: '검단구', label: '검단구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_계양구', name: '계양구', label: '계양구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_남동구', name: '남동구', label: '남동구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_미추홀구', name: '미추홀구', label: '미추홀구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_부평구', name: '부평구', label: '부평구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_서해구', name: '서해구', label: '서해구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_연수구', name: '연수구', label: '연수구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_영종구', name: '영종구', label: '영종구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_옹진군', name: '옹진군', label: '옹진군', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '28_제물포구', name: '제물포구', label: '제물포구', province: '인천광역시', provinceCode: '28', short: '인천' },
  { code: '30_대덕구', name: '대덕구', label: '대덕구', province: '대전광역시', provinceCode: '30', short: '대전' },
  { code: '30_동구', name: '동구', label: '동구(대전)', province: '대전광역시', provinceCode: '30', short: '대전' },
  { code: '30_서구', name: '서구', label: '서구(대전)', province: '대전광역시', provinceCode: '30', short: '대전' },
  { code: '30_유성구', name: '유성구', label: '유성구', province: '대전광역시', provinceCode: '30', short: '대전' },
  { code: '30_중구', name: '중구', label: '중구(대전)', province: '대전광역시', provinceCode: '30', short: '대전' },
  { code: '31_남구', name: '남구', label: '남구(울산)', province: '울산광역시', provinceCode: '31', short: '울산' },
  { code: '31_동구', name: '동구', label: '동구(울산)', province: '울산광역시', provinceCode: '31', short: '울산' },
  { code: '31_북구', name: '북구', label: '북구(울산)', province: '울산광역시', provinceCode: '31', short: '울산' },
  { code: '31_울주군', name: '울주군', label: '울주군', province: '울산광역시', provinceCode: '31', short: '울산' },
  { code: '31_중구', name: '중구', label: '중구(울산)', province: '울산광역시', provinceCode: '31', short: '울산' },
  { code: '36_세종시', name: '세종시', label: '세종시', province: '세종특별자치시', provinceCode: '36', short: '세종' },
  { code: '41_가평군', name: '가평군', label: '가평군', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_고양시', name: '고양시', label: '고양시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_과천시', name: '과천시', label: '과천시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_광명시', name: '광명시', label: '광명시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_광주시', name: '광주시', label: '광주시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_구리시', name: '구리시', label: '구리시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_군포시', name: '군포시', label: '군포시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_김포시', name: '김포시', label: '김포시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_남양주시', name: '남양주시', label: '남양주시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_동두천시', name: '동두천시', label: '동두천시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_부천시', name: '부천시', label: '부천시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_성남시', name: '성남시', label: '성남시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_수원시', name: '수원시', label: '수원시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_시흥시', name: '시흥시', label: '시흥시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_안산시', name: '안산시', label: '안산시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_안성시', name: '안성시', label: '안성시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_안양시', name: '안양시', label: '안양시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_양주시', name: '양주시', label: '양주시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_양평군', name: '양평군', label: '양평군', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_여주시', name: '여주시', label: '여주시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_연천군', name: '연천군', label: '연천군', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_오산시', name: '오산시', label: '오산시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_용인시', name: '용인시', label: '용인시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_의왕시', name: '의왕시', label: '의왕시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_의정부시', name: '의정부시', label: '의정부시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_이천시', name: '이천시', label: '이천시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_파주시', name: '파주시', label: '파주시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_평택시', name: '평택시', label: '평택시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_포천시', name: '포천시', label: '포천시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_하남시', name: '하남시', label: '하남시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '41_화성시', name: '화성시', label: '화성시', province: '경기도', provinceCode: '41', short: '경기' },
  { code: '43_괴산군', name: '괴산군', label: '괴산군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_단양군', name: '단양군', label: '단양군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_보은군', name: '보은군', label: '보은군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_영동군', name: '영동군', label: '영동군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_옥천군', name: '옥천군', label: '옥천군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_음성군', name: '음성군', label: '음성군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_제천시', name: '제천시', label: '제천시', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_증평군', name: '증평군', label: '증평군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_진천군', name: '진천군', label: '진천군', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_청주시', name: '청주시', label: '청주시', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '43_충주시', name: '충주시', label: '충주시', province: '충청북도', provinceCode: '43', short: '충북' },
  { code: '44_계룡시', name: '계룡시', label: '계룡시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_공주시', name: '공주시', label: '공주시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_금산군', name: '금산군', label: '금산군', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_논산시', name: '논산시', label: '논산시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_당진시', name: '당진시', label: '당진시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_보령시', name: '보령시', label: '보령시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_부여군', name: '부여군', label: '부여군', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_서산시', name: '서산시', label: '서산시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_서천군', name: '서천군', label: '서천군', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_아산시', name: '아산시', label: '아산시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_예산군', name: '예산군', label: '예산군', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_천안시', name: '천안시', label: '천안시', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_청양군', name: '청양군', label: '청양군', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_태안군', name: '태안군', label: '태안군', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '44_홍성군', name: '홍성군', label: '홍성군', province: '충청남도', provinceCode: '44', short: '충남' },
  { code: '47_경산시', name: '경산시', label: '경산시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_경주시', name: '경주시', label: '경주시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_고령군', name: '고령군', label: '고령군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_구미시', name: '구미시', label: '구미시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_김천시', name: '김천시', label: '김천시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_문경시', name: '문경시', label: '문경시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_봉화군', name: '봉화군', label: '봉화군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_상주시', name: '상주시', label: '상주시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_성주군', name: '성주군', label: '성주군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_안동시', name: '안동시', label: '안동시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_영덕군', name: '영덕군', label: '영덕군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_영양군', name: '영양군', label: '영양군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_영주시', name: '영주시', label: '영주시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_영천시', name: '영천시', label: '영천시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_예천군', name: '예천군', label: '예천군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_울릉군', name: '울릉군', label: '울릉군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_울진군', name: '울진군', label: '울진군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_의성군', name: '의성군', label: '의성군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_청도군', name: '청도군', label: '청도군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_청송군', name: '청송군', label: '청송군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_칠곡군', name: '칠곡군', label: '칠곡군', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '47_포항시', name: '포항시', label: '포항시', province: '경상북도', provinceCode: '47', short: '경북' },
  { code: '48_거제시', name: '거제시', label: '거제시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_거창군', name: '거창군', label: '거창군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_고성군', name: '고성군', label: '고성군(경남)', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_김해시', name: '김해시', label: '김해시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_남해군', name: '남해군', label: '남해군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_밀양시', name: '밀양시', label: '밀양시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_사천시', name: '사천시', label: '사천시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_산청군', name: '산청군', label: '산청군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_양산시', name: '양산시', label: '양산시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_의령군', name: '의령군', label: '의령군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_진주시', name: '진주시', label: '진주시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_창녕군', name: '창녕군', label: '창녕군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_창원시', name: '창원시', label: '창원시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_통영시', name: '통영시', label: '통영시', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_하동군', name: '하동군', label: '하동군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_함안군', name: '함안군', label: '함안군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_함양군', name: '함양군', label: '함양군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '48_합천군', name: '합천군', label: '합천군', province: '경상남도', provinceCode: '48', short: '경남' },
  { code: '50_서귀포시', name: '서귀포시', label: '서귀포시', province: '제주특별자치도', provinceCode: '50', short: '제주' },
  { code: '50_제주시', name: '제주시', label: '제주시', province: '제주특별자치도', provinceCode: '50', short: '제주' },
  { code: '51_강릉시', name: '강릉시', label: '강릉시', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_고성군', name: '고성군', label: '고성군(강원)', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_동해시', name: '동해시', label: '동해시', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_삼척시', name: '삼척시', label: '삼척시', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_속초시', name: '속초시', label: '속초시', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_양구군', name: '양구군', label: '양구군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_양양군', name: '양양군', label: '양양군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_영월군', name: '영월군', label: '영월군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_원주시', name: '원주시', label: '원주시', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_인제군', name: '인제군', label: '인제군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_정선군', name: '정선군', label: '정선군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_철원군', name: '철원군', label: '철원군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_춘천시', name: '춘천시', label: '춘천시', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_태백시', name: '태백시', label: '태백시', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_평창군', name: '평창군', label: '평창군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_홍천군', name: '홍천군', label: '홍천군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_화천군', name: '화천군', label: '화천군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '51_횡성군', name: '횡성군', label: '횡성군', province: '강원특별자치도', provinceCode: '51', short: '강원' },
  { code: '52_고창군', name: '고창군', label: '고창군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_군산시', name: '군산시', label: '군산시', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_김제시', name: '김제시', label: '김제시', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_남원시', name: '남원시', label: '남원시', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_무주군', name: '무주군', label: '무주군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_부안군', name: '부안군', label: '부안군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_순창군', name: '순창군', label: '순창군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_완주군', name: '완주군', label: '완주군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_익산시', name: '익산시', label: '익산시', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_임실군', name: '임실군', label: '임실군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_장수군', name: '장수군', label: '장수군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_전주시', name: '전주시', label: '전주시', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_정읍시', name: '정읍시', label: '정읍시', province: '전북특별자치도', provinceCode: '52', short: '전북' },
  { code: '52_진안군', name: '진안군', label: '진안군', province: '전북특별자치도', provinceCode: '52', short: '전북' },
];
