export const SEOUL_DISTRICT_NAME: Record<string, string> = {
  'seoul-jongno': '종로구',
  'seoul-jung': '중구',
  'seoul-yongsan': '용산구',
  'seoul-seongdong': '성동구',
  'seoul-gwangjin': '광진구',
  'seoul-dongdaemun': '동대문구',
  'seoul-jungnang': '중랑구',
  'seoul-seongbuk': '성북구',
  'seoul-gangbuk': '강북구',
  'seoul-dobong': '도봉구',
  'seoul-nowon': '노원구',
  'seoul-eunpyeong': '은평구',
  'seoul-seodaemun': '서대문구',
  'seoul-mapo': '마포구',
  'seoul-yangcheon': '양천구',
  'seoul-gangseo': '강서구',
  'seoul-guro': '구로구',
  'seoul-geumcheon': '금천구',
  'seoul-yeongdeungpo': '영등포구',
  'seoul-dongjak': '동작구',
  'seoul-gwanak': '관악구',
  'seoul-seocho': '서초구',
  'seoul-gangnam': '강남구',
  'seoul-songpa': '송파구',
  'seoul-gangdong': '강동구',
};
